//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.07 at 01:21:03 PM EDT 
//


package order;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cor_order_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cor_customer_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cor_customer_payment_method_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cor_order_status_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cor_date_order_paid" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="cor_der_total_order_price" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="cor_other_order_details" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "corOrderId",
    "corCustomerId",
    "corCustomerPaymentMethodId",
    "corOrderStatusCode",
    "corDateOrderPaid",
    "corDerTotalOrderPrice",
    "corOtherOrderDetails"
})
@XmlRootElement(name = "tbl_customer_orders")
public class TblCustomerOrders {

    @XmlElement(name = "cor_order_id")
    protected int corOrderId;
    @XmlElement(name = "cor_customer_id", required = true)
    protected String corCustomerId;
    @XmlElement(name = "cor_customer_payment_method_id", required = true)
    protected String corCustomerPaymentMethodId;
    @XmlElement(name = "cor_order_status_code", required = true)
    protected String corOrderStatusCode;
    @XmlElement(name = "cor_date_order_paid", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar corDateOrderPaid;
    @XmlElement(name = "cor_der_total_order_price", required = true)
    protected BigDecimal corDerTotalOrderPrice;
    @XmlElement(name = "cor_other_order_details", required = true)
    protected String corOtherOrderDetails;

    /**
     * Gets the value of the corOrderId property.
     * 
     */
    public int getCorOrderId() {
        return corOrderId;
    }

    /**
     * Sets the value of the corOrderId property.
     * 
     */
    public void setCorOrderId(int value) {
        this.corOrderId = value;
    }

    /**
     * Gets the value of the corCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorCustomerId() {
        return corCustomerId;
    }

    /**
     * Sets the value of the corCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorCustomerId(String value) {
        this.corCustomerId = value;
    }

    /**
     * Gets the value of the corCustomerPaymentMethodId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorCustomerPaymentMethodId() {
        return corCustomerPaymentMethodId;
    }

    /**
     * Sets the value of the corCustomerPaymentMethodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorCustomerPaymentMethodId(String value) {
        this.corCustomerPaymentMethodId = value;
    }

    /**
     * Gets the value of the corOrderStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorOrderStatusCode() {
        return corOrderStatusCode;
    }

    /**
     * Sets the value of the corOrderStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorOrderStatusCode(String value) {
        this.corOrderStatusCode = value;
    }

    /**
     * Gets the value of the corDateOrderPaid property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCorDateOrderPaid() {
        return corDateOrderPaid;
    }

    /**
     * Sets the value of the corDateOrderPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCorDateOrderPaid(XMLGregorianCalendar value) {
        this.corDateOrderPaid = value;
    }

    /**
     * Gets the value of the corDerTotalOrderPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCorDerTotalOrderPrice() {
        return corDerTotalOrderPrice;
    }

    /**
     * Sets the value of the corDerTotalOrderPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCorDerTotalOrderPrice(BigDecimal value) {
        this.corDerTotalOrderPrice = value;
    }

    /**
     * Gets the value of the corOtherOrderDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorOtherOrderDetails() {
        return corOtherOrderDetails;
    }

    /**
     * Sets the value of the corOtherOrderDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorOtherOrderDetails(String value) {
        this.corOtherOrderDetails = value;
    }

}
